try {
  let a = 5;
  let b = 0;
  let c = a / b;
}
catch{
  console.log("error");
}
finally{
  console.log("finally");
}
